#!/bin/sh
set -e

echo "Running format and lint for backend..."
cd backend
npm run format
npm run lint

echo "Running format and lint for backend-cdk..."
cd ../backend-cdk
npm run format
npm run lint

echo "Pre-push checks passed."
