#!/bin/sh
set -e

echo "Running prettier and lint for backend..."
cd backend
npm run prettier
npm run lint

echo "Running prettier and lint for backend-cdk..."
cd ../backend-cdk
npm run prettier
npm run lint

echo "Running prettier and lint for frontend..."
cd ../frontend
npm run prettier
npm run lint

echo "Running prettier and lint for frontend-cdk..."
cd ../frontend-cdk
npm run prettier
npm run lint

echo "Pre-commit checks passed."
