export const CATEGORY_TYPE = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;

export const TRANSACTION_TYPE = {
  INCOME: CATEGORY_TYPE.INCOME,
  EXPENSE: CATEGORY_TYPE.EXPENSE,
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
} as const;
